### ISSUE TITLE
Only Uses One of the two controllers at the house

### ISSUE THREAD

**Issue by yestrdave** [valiquette/homebridge-rachio-irrigation#31]
I believe only one controller can be used at a time?  Looks like its trying to add the first one.  Everything is online and functioning in Rachio software.
[12/11/2021, 6:58:28 AM] [Rachio] Adding controller Guest House Rachio found at the configured location: Home
[12/11/2021, 6:58:28 AM] [Rachio] Skipping controller Guest House Rachio at Home, not found at the configured location: Home
[12/11/2021, 6:58:28 AM] [Rachio] Skipping controller Big Garage Controller at Home, not found at the configured location: Home
[12/11/2021, 6:58:28 AM] [Rachio] Adding controller Big Garage Controller found at the configured location: Home
[12/11/2021, 6:58:28 AM] [Rachio] Found device Big Garage Controller status ONLINE

Changed address. All Addresses are the same.  

Running HomeBridge on Synology Docker

**Comment by yestrdave** [comment]
I found if I removed the address completely both controllers showed up, even though they were at the same address.

This is a very nice implementation --Great work.

**Comment by valiquette** [comment]
I do see a problem with the line of code responsible for that, which I'll want to fix and should be simple. It should have supported your use case.  If you leave the location in the plugin config blank it skips this check and would work which is what you did.

**Comment by valiquette** [comment]
It would be helpful for me to see the responses during the plugin startup. If it is possible could you enable debug logging, maybe truncate it and restart this plugin, save the log and attach it here?  Thanks

**Comment by yestrdave** [comment]
I deleted the physical address and both controllers are showing up. Would you like me to try something else?

Also I have my port forwarding set up correctly and can access homebridge through 12453.  However doesn’t seam to be updating the state. I reset the bridge and it seamed to work then stopped.

**Comment by valiquette** [comment]
I am interested in your debug log file that all it would be helpful since I do not have 2 controls to test against, that all.

**Comment by yestrdave** [comment]
Sorry I was reading emails.  I see all responses now.  Would you like me to add the physical address back in and run in debug mode?

**Comment by valiquette** [comment]
that would not be required, I am looking for the info Rachio send back for two of the API call when it starts up.

**Comment by valiquette** [comment]
you do need to run debug mode but the address is optional

**Comment by yestrdave** [comment]
I have the log file.  If I post it is there any information in here I need to delete ? Im assuming the log will be public.

**Comment by yestrdave** [comment]
let me know if you need anything else.  Happy to help.  Please also see if there is a reason webhook isn't updating Homekit

[homebridge.log (1).txt](https://github.com/valiquette/homebridge-rachio-irrigation/files/7697308/homebridge.log.1.txt)

**Comment by valiquette** [comment]
I am a little stumped on the webhook not updating, not sure right now why that would be. Is this not updating on just one device or both? The log attached earlier did not have any zone starts/stops, would it be possible to get a debug log, again truncate it then run a few zones on each device and capture that. Thanks

**Comment by valiquette** [comment]
I published beta version (1.2.6) which should correct the location matching issue reported. please let me know it it resolves your issues. It may have causes some webhook issues, keep an eye on that. it that is still an issue I will need to see the debug log..
