### ISSUE TITLE
Home App Issues

### ISSUE THREAD

**Issue by a-rodriguez** [valiquette/homebridge-rachio-irrigation#40]
Thank you for creating this plugin!

I was able to setup the plugin and configure Webhook Relay. When I look at the Rachio on the Home app and tap open the Rachio I have a blank page. See screenshot below. I appreciate any suggestions or help you can provide.

![IMG_0507](https://user-images.githubusercontent.com/17552897/160240078-d16038bf-3dde-4fed-81e3-76536fcd9910.PNG)

**Comment by valiquette** [comment]
Do you see the sprinklers in hombridge? if so try removing the bridge from homelike and re add it. if things do not seem right in Homebridge. pay close attention to the logging, it may point you to the correct area.
If you enter an address, make sure it matches exactly, or just remove it from the plugin config.

**Comment by a-rodriguez** [comment]
I uninstalled that plugin and unchecked controller standby, schedules and zones. Its working now. Thanks again for this great plugin.
