### ISSUE TITLE
Raedme Suggestion (?) re: webhook public endpoint address

### ISSUE THREAD

**Issue by rucknapucknavitz** [valiquette/homebridge-rachio-irrigation#42]
This is a great plugin for those of us with older an Rachio, thank you! 

Wasn’t sure where to put this in case it’s helpful to someone else, as it took me a long time to figure out that I was **NOT** supposed to include the `https://` before my public endpoint address.

I was getting an error saying that the address couldn’t be validated and that webhooks were disabled.

Had I read your readme with precision , I would have seen that you did not include the `https://`, but since I copied my endpoint address directly from the webhookrelay site via their copy button, it was included.

Thanks again!

**Comment by valiquette** [comment]
Thanks for the comment, but I have a question. That error is checking to see if the IP or domain is formatted correctly. Rachio will not except an https. In the config it asked for External IP address for this server or Domain to be used to receive webhook requests. Domain being the key, but assuming this was glossed over. if this read External IP address for this server or Domain to be used to receive webhook requests. note For webhook relay just use the domain portion don't include http://
I can also improve the error message to include something similar. Would these have helped?

**Comment by valiquette** [comment]
addressed in latest release
