### ISSUE TITLE
Homekit valves shows "on" after a manual run

### ISSUE THREAD

**Issue by OttoVonSkidmark** [valiquette/homebridge-rachio-irrigation#43]
I love the plugin (it finally showed Rachip in the Apple Home app without Rachio actually fixing issues on their end!  W00t!!
One quick question - Homekit valves shows "on" after a manual run completes even though the sprinkler valves are off (and show "off" in Rachio)

This behavior does not present itself with scheduled runs, only with manual "quick runs" initiated through Homekit (through the Apple home app - I have not tried it through Eve or any other Homekit frontend)

**Comment by valiquette** [comment]
I am confused about scheduled vs manual, but sounds like web hooks. Double check that you have web hooks configured correctly. Does homekit reflect on contact if started from Rachio?

**Comment by OttoVonSkidmark** [comment]
Scheduled - my weekly schedule as managed by Rachio
Manual - me running a valve on my own through homekit

Homekit does not reflect the correct status if a run is initiated through Rachio.  I'll check webhooks when I get home in a few days!  I've never added webhooks to my home IP address before so I probably horked up the config.

Thanks!

**Comment by valiquette** [comment]
Sounds like webhooks. Probably the port forwarding piece. The readme and the logging should help you.
