### ISSUE TITLE
Getting an error asking for specific versions of Node

### ISSUE THREAD

**Issue by sebastiangoldstein** [valiquette/homebridge-rachio-irrigation#45]
Getting this error:

The plugin "homebridge-rachio-irrigation" requires Node.js version of ^14.20.0 || ^16.18.0 || ^18.11.0 which does not satisfy the current Node.js version of v16.13.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF

I am running 

Node.js Version | v16.13.0

**Comment by valiquette** [comment]
That should just be a warning. when do you see that message? This is expected since 16.13.0 is older then 16.18.0.
it probably would be best if you ran "hb-service update-node 16" or "hb-service update-node 18" from the HB terminal and upgrade your node js version.
