### ISSUE TITLE
Webhook setup question?

### ISSUE THREAD

**Issue by lnjustin** [valiquette/homebridge-rachio-irrigation#46]
I'm trying to set this up, but a few things are unclear to me from the readme. Can you update the readme to address these aspects:

(1) How do you figure out which ports to use for the port forwarding? I understand the IP address parts, but don't know what ports to use.
(2) if you use DDNS, I assume you put the domain name in the config file, right?
(3) the account detail in the config file, is for Rachio correct?

To be clear, I guessed at the right values for the above and have it working. Just would be a bit clearer if the readme spelled it out more. Thanks for a great plugin!

**Comment by valiquette** [comment]
I can take a look, there are details and default behavior in the config UI that address some of this very clearly,  which to your point are not explicitly called out in the readme. Can I ask are you using homebridge headless? or using this plugin with HOOBs? HOOBs seems to be notorious for butchering config UI and even omitting required fields.

1) there is no correct value to send or receive, only that you forward the values you choose. 
2) DDNS, yes it should replace an IP, but I am not sure i am allowing it, I have not had a request to support that with port forwarding.
3) account detail in the config? You only need a the API key for Rachio, the config file has a user and password which are arbitrary and only used to validate an incoming webhook if you choose to use basic authorization.
