### ISSUE TITLE
run time adjustment?

### ISSUE THREAD

**Issue by lnjustin** [valiquette/homebridge-rachio-irrigation#47]
An [unverified plugin](https://www.npmjs.com/package/@leehendricks/homebridge-rachio-platform) has a neat option to quickly set the run time of a zone. It's just a "settings" button that allows a quick adjustment to the default run time setting for that run. Check it out. Is that easy to add to this plugin?

**Comment by valiquette** [comment]
It is already there, if you are running with this being displayed as a irrigation system go to the setting and you will see a list of zones, just expand them and set you default run time. For individual zone display it is just in the settings, like the example you referenced.
