### ISSUE TITLE
 Help with pairing with homekit

### ISSUE THREAD

**Issue by LarryT8959** [valiquette/homebridge-rachio-irrigation#49]
Hello,
I've installed the plugin and it seems to be loading okay. My question is why are there three switches along with the controller icon in homekit? Is that normal or did I install something incorrectly?
Thanks

**Comment by valiquette** [comment]
There are 3 additional switches in the config which are true be default, (I should change that). in Homebridge that should be really clear. If Your using HOOBS you may need to check the config file. If you want the gone just make sure the config looks like.
	"show_standby": false,
	"show_runall": false,
	"show_schedules": false,
Also you can keep some and make them separate in HomeKit by opening the properties and selecting the show as separate tiles.
