### ISSUE TITLE
Sprinkler not registering off in Homekit

### ISSUE THREAD

**Issue by 3aceskelsen** [valiquette/homebridge-rachio-irrigation#5]
Sprinklers turn off and on with the toggle in HomeKit, but once turned on, it won’t say turned off even though nothing is running.

**Comment by valiquette** [comment]
This sounds like the web hook connection or port fowarding is not correct. You should see zone complete messages in the log . You can send me a copy of you config without your API key and a snippet of the logging right after a restart.

**Comment by valiquette** [comment]
If it is your preference to use this without web hooks then estimating when the zone turns off and reflecting that would be functionality I would have to account for. Not a bad idea but i am not sure if this was you intent or not.

**Comment by valiquette** [comment]
fixed in v1.10

**Comment by 3aceskelsen** [comment]
Thanks, it’s working great!
