### ISSUE TITLE
[Homebridge UI] Failed to refresh characteristics for <DEVICENAME>: connect ECONNRESET 192.168.1.105:51912

### ISSUE THREAD

**Issue by TheTrailGeek** [valiquette/homebridge-rachio-irrigation#53]
When I enable this plugin, my logs fill up with the following for each device in my Homebridge Setup:

[Homebridge UI] Failed to refresh characteristics for <DEVICENAME>: connect ECONNRESET 192.168.1.105:51912

I try to add to home and get "Accessory Not Found".  Once I disable the plugin, things go back to normal and everything works as expected.  Thank you for any help you can provide.

**Comment by TheTrailGeek** [comment]
OS macOS Catalina
Homebridge 1.6.1
Node v18.16.0
The only thing odd in the log is a huge list of devices showing the "Failed to refresh" errors after enabling the Rachio plugin.  Rachio shows it's up and running, but when I try to add it to Home using the QR code, it allows me to click to add the bridge, but then it just spins and eventually fails with "Accessory Not Found".  

`{
    "bridge": {
        "name": "Homebridge",
        "username": "xxxxx",
        "port": xxxxx,
        "pin": "xxxxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "units": "us",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "xxxxx",
                    "service": "weatherunderground",
                    "key": "xxxxx",
                    "stationId": "xxxxx",
                    "language": "en",
                    "compatibility": "home",
                    "conditionCategory": "detailed",
                    "now": true,
                    "extraHumidity": false
                }
            ],
            "platform": "WeatherPlus"
        },
        {
            "name": "Govee",
            "batteryThreshold": 25,
            "debug": false,
            "humidityOffset": 0,
            "platform": "GoveeHomebridgePlugin"
        },
        {
            "platform": "Hubitat-v2",
            "name": "Hubitat-v2",
            "app_url_local": "http://192.168.xx.xx/apps/api/",
            "app_url_cloud": "xxxxx",
            "app_id": 487,
            "app_platform": "Hubitat",
            "use_cloud": false,
            "access_token": "xxxxx",
            "temperature_unit": "F",
            "validateTokenId": true,
            "adaptive_lighting": true,
            "consider_fan_by_name": true,
            "consider_light_by_name": true,
            "adaptive_lighting_offset": 0,
            "round_levels": true,
            "logConfig": {
                "debug": false,
                "showChanges": true
            }
        },
        {
            "refreshToken": "xxxxx",
            "platform": "Ring"
        },
        {
            "controllers": [
                {
                    "address": "192.168.xx.xx",
                    "password": "xxxxx",
                    "username": "xxxxx"
                }
            ],
            "platform": "UniFi Protect"
        },
        {
            "name": "Nest",
            "refreshToken": "xxxxx",
            "platform": "Nest"
        },
        {
            "name": "Rachio",
            "api_key": "xxxxx",
            "default_runtime": 10,
            "runtime_source": 0,
            "use_irrigation_display": true,
            "show_standby": true,
            "show_runall": true,
            "show_schedules": true,
            "external_IP_address": "xxxxx",
            "internal_IP_address": "127.0.0.1",
            "external_webhook_port": 12453,
            "internal_webhook_port": 27543,
            "use_basic_auth": true,
            "user": "xxxxx",
            "password": "xxxxx",
            "delete_webhooks": false,
            "showAPIMessages": true,
            "showWebhookMessages": true,
            "platform": "rachio"
        }
    ],
    "disabledPlugins": []
}`

**Comment by valiquette** [comment]
Was this plugin ever paired with HomeKit? or the plugin re installed?

**Comment by TheTrailGeek** [comment]
It doesn't show under "Remove Single Cached Accessory" and has never showed under "Accessories" when enabled.  I just went into "Unpair Bridges / Cameras / TVs / External Accessories" and removed it and then enabled the plugin again and it's showing under "Unpair Bridges / Cameras / TVs / External Accessories" again, but not under the "Accessories" tab.  The "Failed to refresh" errors came back as soon as I enabled the plugin and I'm still getting "Accessory Not Found" when trying to add to "Home" on my iPhone.

**Comment by valiquette** [comment]
Can you enable debug logging, clear the log then restart this plugin and attach the log output?

**Comment by TheTrailGeek** [comment]
`[5/24/2023, 10:16:09 AM] [Rachio] Child bridge process ended
[5/24/2023, 10:16:09 AM] [Rachio] Process Ended. Code: 143, Signal: null
[5/24/2023, 10:16:16 AM] [Rachio] Restarting Process...
[5/24/2023, 10:16:16 AM] [Rachio] Launched child bridge with PID 63597
[5/24/2023, 10:16:16 AM] Registering platform 'homebridge-rachio-irrigation.rachio'
[5/24/2023, 10:16:16 AM] [Rachio] Loaded homebridge-rachio-irrigation v1.2.21 child bridge successfully
[5/24/2023, 10:16:16 AM] Loaded 0 cached accessories from cachedAccessories.0E4EAC9B6459.
[5/24/2023, 10:16:16 AM] [Rachio] Starting Rachio Platform with homebridge API 2.7
[5/24/2023, 10:16:16 AM] [Rachio] using IPv4 webhook external address
[5/24/2023, 10:16:16 AM] Publishing bridge accessory (name: Rachio, publishInfo: {
  username: 'xxxxxx',
  port: 34356,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: undefined
}).
[5/24/2023, 10:16:16 AM] [Rachio] Fetching build info...
[5/24/2023, 10:16:16 AM] [Rachio] Getting Person info...
[5/24/2023, 10:16:16 AM] [Rachio] Retrieving Person Info
[5/24/2023, 10:16:16 AM] Homebridge v1.6.1 (HAP v0.11.1) (Rachio) is running on port 34356.
[5/24/2023, 10:16:17 AM] [Rachio] get person info response {
  "id": "xxxxx"
}
[5/24/2023, 10:16:17 AM] [Rachio] Found Person ID xxxxx
[5/24/2023, 10:16:17 AM] [Rachio] Getting Person ID info...
[5/24/2023, 10:16:17 AM] [Rachio] Retrieving Person ID
[5/24/2023, 10:16:17 AM] [Rachio] get person id response {
  "createDate": 1684879503000,
  "id": "xxxxx",
  "username": "xxxxx",
  "fullName": "xxxxx",
  "email": "xxxxx",
  "devices": [],
  "deleted": false
}
[5/24/2023, 10:16:17 AM] [Rachio] Found Account for username xxxxx
[5/24/2023, 10:16:17 AM] [Rachio] Getting Location info...
[5/24/2023, 10:16:17 AM] [Rachio] Getting Location List
[5/24/2023, 10:16:17 AM] [Rachio] get list locations response {
  "locationSummary": []
}
[5/24/2023, 10:16:17 AM] [Rachio] Will listen for Webhooks matching Webhook ID homebridge-Rachio
[5/24/2023, 10:16:17 AM] [Rachio] This server is listening on port 27543.
[5/24/2023, 10:16:17 AM] [Rachio] Using HTTP basic authentication for Webhooks
[5/24/2023, 10:16:17 AM] [Rachio] Make sure your router has port fowarding turned on for port 12453 to this server`s IP address and this port 27543, unless you are using a relay service.
[5/24/2023, 10:16:18 AM] [Rachio] Rachio Platform finished loading`

**Comment by valiquette** [comment]
are these the actual responses?
5/24/2023, 10:16:17 AM] [Rachio] get person id response { "createDate": 1684879503000, "id": "xxxxx", "username": "xxxxx", "fullName": "xxxxx", "email": "xxxxx", "devices": [], "deleted": false } 
10:16:17 AM] [Rachio] get list locations response { "locationSummary": [] } 
or did you remove the info inside [] ?

You should be seeing a lot if info that should make sense to your deployment

**Comment by TheTrailGeek** [comment]
The "xxxxx" are the only things I changed.

**Comment by valiquette** [comment]
What kind of device are you trying to add?

**Comment by TheTrailGeek** [comment]
Ah, my apologies for not noticing that.  🤦🏼‍♂️

**Comment by valiquette** [comment]
V1.3.0 beta no supports the hose timer.
