### ISSUE TITLE
New Smart Hose Timer API

### ISSUE THREAD

**Issue by vponnusamy** [valiquette/homebridge-rachio-irrigation#63]
Any possibility for this to work with your plugin in the future?

https://rachio.readme.io/reference/smart-hose-timer-data-objects

**Comment by valiquette** [comment]
I was planning on it, but I don't have a timer to develop against at this time.

**Comment by valiquette** [comment]
I did order a unit. This should be a fairly easy thing to add in.

**Comment by valiquette** [comment]
V1.3.0 beta no supports the hose timer. Let me know how this works for you.

**Comment by vponnusamy** [comment]
Amazing--just installed the beta and see them showing up exactly as expected!
