### ISSUE TITLE
HomeKit Automations with this plugin?

### ISSUE THREAD

**Issue by ethanopp** [valiquette/homebridge-rachio-irrigation#64]
Is it possible to create automations in HomeKit off any of the sensors provided in this plugin?

I used to have Rachio HomeKit integration set up directly from their app but the iOS 17 upgrade broke that. When it was working though, I had an automation "when sprinklers turned on, do x".

I have this plugin setup and also got the Webhook relay working, I can see the device in my HomeKit, but for some reason cant seem to get any of the devices to show when I try to create an automation and click "when an accessory is controlled"

**Comment by valiquette** [comment]
HomeKit does not allow irrigation as part of their automation or scenes. I am a surprised you had an option under the Rachio integration. 
This plugin will allow you to create a switch to start a defined schedule but there is no sensor to key off of for when a zone or controller is running.
Can I ask what you are looking for, Controller running or a specific zone?

**Comment by ethanopp** [comment]
I dont recall exactly how I had it set up, I believe it was a switch though.

I only have 1 schedule that goes through all of my zones. I just want to be able to set up an automation so it knows if the lawn is wet, to not send my automowers out.

So really any sort of way to know if any zone ran would work... or a trigger to know that the controller started a schedule would work too

**Comment by valiquette** [comment]
I would have to add a sensor to allow that.

**Comment by ethanopp** [comment]
Ah okay - please consider this a feature request then!

**Comment by rickoco** [comment]
hello @valiquette is it possible to setup water schedules with the rachio smart valve in HomeKit using your homebridge plugin?

**Comment by valiquette** [comment]
Automation for water is not allowed in HomeKit. You would have to rely on Rachio for this one.

**Comment by rickoco** [comment]
thx @valiquette - once a schedule is setup in Rachio, does your plugin pull "Pause Watering 1 day" (or similar) functions into HomeKit?

**Comment by valiquette** [comment]
It does for a controller but not for the hose timer. I could pull the schedules in as a switch, but Rachio did not provide and API to manually start or stop a schedule so I never took it any further than a manual start stop. I might be able to pull in a schedule and work with it.
Could you describe in detail what you would like to do?

**Comment by rickoco** [comment]
Ideally, it would be great to be able to create and edit both Schedules & Automation in HomeKit.  Failing that, create and edit schedules in Rachio and be able to skip the schedule for some number of days, say 1, 2 or 3 days from within HomeKit (in addition to the manual start / stop you already support).  I have 2 Rachio Wifi hubs each with 1 valve connected.

**Comment by rickoco** [comment]
Hi @valiquette - any thoughts on this?

**Comment by valiquette** [comment]
I can't support this request.
